### ISSUE TITLE
Missing title-map file while converting to DPR format

### ISSUE THREAD

**Issue by jblagoja** [SapienzaNLP/relik#10]
Hi ReLiK team,

I appreciate your work, please keep up the good work!

I am following your step-by-step guide in the section 📚 Before You Start, and faced an error when converting the BLINK dataset (windowed) in the DPR format by running the following cli command: 
relik data convert-to-dpr \
  data/blink/processed/blink-train-kilt-relik-windowed.jsonl \
  data/blink/processed/blink-train-kilt-relik-windowed-dpr.jsonl \
  data/kb/wikipedia/documents.jsonl \
  --title-map data/kb/wikipedia/title_map.json

The error that I am getting is the following:
FileNotFoundError: [Errno 2] No such file or directory: 'data/kb/wikipedia/title_map.json'

Before, I downloaded the Wikipedia index and stored in the following path: data/kb/wikipedia/documents.json.

I have tried the above cli command without the --title-map argument which generated empty file.

May I ask you from where to get the title-map, or is there some procedure how to create/generate the required file (title_map.json).

Thanks ahead and best regards,
Blagoja

**Comment by LittlePea13** [comment]
Sorry for the late reply, the title map is the one from EntQA to ensure correct comparisons with them if you are working with the Blink index and want to map entities in AIDA to the Entity titles in it (since it was created years after AIDA, some entities had changed names in Wikipedia).

You can find it here: https://github.com/WenzhengZhang/EntQA/blob/main/title_map.json

For any other index or dataset you may not need a title mapping or may need to tailor it to your specific use case.
