### ISSUE TITLE
On relik import, OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by stevereiner** [SapienzaNLP/relik#14]
After 
pip install relik 
in a virtual env

With just
from relik import Relik
or
import relik
Get
OverflowError: Python int too large to convert to C long

python 3.12.6
Windows11

**Comment by stevereiner** [comment]
worked on ubuntu 22.04 with virt env python 3.10.12
on ubuntu non virt env python 3.12.4
error can't import name _imaging  onnx config

**Comment by Riccorl** [comment]
Hi! Thanks for reporting the issue! It appears to be related to Python 3.12, as seen in similar issues on [StackOverflow](https://stackoverflow.com/questions/77274572/multiqc-modulenotfounderror-no-module-named-imp). Specifically, the problem seems to involve the wandb module. I recommend using Python 3.11 until the dependencies are updated.

We will enforce the Python version to be lower than 3.12 for the next releases until the issue is fixed.
